version: '3'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "5259:5259"
    restart: unless-stopped
    depends_on:
      - camunda